language: python

env:
  global:
    - PYTHON36="3.6.8"
    - PYTHON37="3.7.2"
    - PYTHON38="3.8-dev"
matrix:
  include: 
    - name: "Windows: Python3.7"
      os: windows
      language: sh
      env: PYTHON_VERSION=${PYTHON37}
      before_install: 
        - source scripts/windows.sh
        
#     - name: "Windows: Python3.8-dev"
#       os: windows
#       language: sh
#       env: PYTHON_VERSION=${PYTHON38}
#       before_install: 
#         - source scripts/windows.sh
  
install:
  - python --version
  - pip --version
  - pip install -rrequirements.txt
  - pip install -rrequirements_dev.txt
  - python setup.py install
  
script: 
  - python setup.py test
