sudo: false
language: python
cache: pip
python:
  - 3.5
  - 3.6
env:
  TOXENV=py

matrix:
  fast_finish: true
  allow_failures:
  - os:  osx
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=fix-lint
    - os: osx
      language: generic

before_install:
 - pyenv versions
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis-osx; fi
 - ls

install:
  - pip install -U six
  - pip install --pre -U tox
  - ls

script:
  - tox

after_success:
- if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
