build: false  # Not a C# project
environment:
  matrix:
    - TOXENV: py35
    - TOXENV: py36

matrix:
  fast_finish: true

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

test_script:
  - C:\Python36\scripts\tox

# after_test:
#   - C:\Python36\scripts\tox -e coverage,codecov

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
