build: false  # Not a C# project
environment:
  matrix:
    - TOXENV: py35
    - TOXENV: py36

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install --pre -U tox
  - C:\Python36\python -m pip install -rrequirements_dev.txt

test_script:
  - C:\Python36\scripts\tox
