build: false  # Not a C# project
environment:
  matrix:
    - TOXENV: py35
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
    - TOXENV: py36

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install --pre -U tox
  - C:\Python36\python -m pip install -rrequirements_dev.txt

test_script:
  - C:\Python36\scripts\tox

# after_test:
#   - C:\Python36\scripts\tox -e coverage,codecov

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
